In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('./dataset/train_dataset.csv', index_col='ID')
X_test = pd.read_csv('./dataset/test_dataset.csv', index_col='ID')
df.head()

,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
ID,,,,,,,,,,,,,,,,,,,
7135,1654,CL,D-penicillamine,19581,F,N,N,Y,N,0.3,279.0,2.96,84.0,1500.8,99.43,109.0,293.0,10.2,4.0
7326,41,C,D-penicillamine,22880,F,NaN,N,NaN,N,0.3,NaN,2.96,NaN,1835.4,26.35,131.0,308.0,10.8,1.0
7254,297,D,NaN,27957,F,N,N,NaN,N,0.3,328.0,2.64,4.0,NaN,NaN,116.0,194.0,10.3,3.0
3135,1872,C,D-penicillamine,21111,F,NaN,Y,Y,N,0.3,302.0,2.02,49.0,NaN,26.35,NaN,NaN,10.5,4.0
2483,939,CL,D-penicillamine,18061,F,NaN,NaN,NaN,N,0.5,344.0,3.11,91.0,NaN,104.56,NaN,306.0,11.4,2.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6800 entries, 7135 to 4826
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   N_Days         6800 non-null   int64
 1   Status         6800 non-null   object
 2   Drug           4775 non-null   object
 3   Age            6800 non-null   int64
 4   Sex            6800 non-null   object
 5   Ascites        4554 non-null   object
 6   Hepatomegaly   4373 non-null   object
 7   Spiders        4210 non-null   object
 8   Edema          6800 non-null   object
 9   Bilirubin      6800 non-null   float64
 10  Cholesterol    3699 non-null   float64
 11  Albumin        6800 non-null   float64
 12  Copper         4644 non-null   float64
 13  Alk_Phos       4302 non-null   float64
 14  SGOT           4698 non-null   float64
 15  Tryglicerides  3988 non-null   float64
 16  Platelets      6462 non-null   float64
 17  Prothrombin    6645 non-null   float64
 18  Stage          6800 non-null   float64
dtypes: float64(10), int64(2), object(7)
memory usage: 1.0+ MB

In [4]:
df.describe()

,N_Days,Age,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
count,6800.000000,6800.000000,6800.000000,3699.000000,6800.000000,4644.000000,4302.000000,4698.000000,3988.000000,6462.000000,6645.000000,6800.000000
mean,1664.055441,22863.223529,1.806147,294.575831,3.036118,68.569121,1802.951464,79.554427,133.857823,293.306097,11.231031,3.157206
std,1332.308135,4671.135682,3.218009,128.085317,0.528164,59.637733,1618.550339,43.433832,47.291444,115.146088,1.123444,0.993059
min,41.000000,9598.000000,0.300000,120.000000,1.960000,4.000000,289.000000,26.350000,33.000000,62.000000,9.000000,1.000000
25%,537.000000,19416.500000,0.300000,204.000000,2.680000,26.000000,1122.650000,35.290000,114.000000,213.000000,10.500000,2.000000
50%,1443.000000,23367.000000,0.400000,312.000000,3.020000,68.000000,1563.150000,88.505000,128.000000,285.000000,11.100000,4.000000
75%,2519.000000,27125.500000,1.800000,353.000000,3.390000,91.000000,2013.250000,110.672500,141.000000,365.000000,11.700000,4.000000
max,4795.000000,28650.000000,28.000000,1775.000000,4.640000,588.000000,13862.400000,340.480000,498.000000,563.000000,18.000000,4.000000

In [5]:
df.isna().sum()

N_Days              0
Status              0
Drug             2025
Age                 0
Sex                 0
Ascites          2246
Hepatomegaly     2427
Spiders          2590
Edema               0
Bilirubin           0
Cholesterol      3101
Albumin             0
Copper           2156
Alk_Phos         2498
SGOT             2102
Tryglicerides    2812
Platelets         338
Prothrombin       155
Stage               0
dtype: int64

In [6]:
df.select_dtypes(include=(['int64', 'float64'])).isna().sum()

N_Days              0
Age                 0
Bilirubin           0
Cholesterol      3101
Albumin             0
Copper           2156
Alk_Phos         2498
SGOT             2102
Tryglicerides    2812
Platelets         338
Prothrombin       155
Stage               0
dtype: int64

In [7]:
df.select_dtypes(include=(['int64', 'float64'])).isna().sum()
df_num_col = df.select_dtypes(include=(['int64', 'float64'])).columns
for c in df_num_col:
    df[c].fillna(df[c].median(), inplace=True)

df.select_dtypes(include=(['int64', 'float64'])).isna().sum()

N_Days           0
Age              0
Bilirubin        0
Cholesterol      0
Albumin          0
Copper           0
Alk_Phos         0
SGOT             0
Tryglicerides    0
Platelets        0
Prothrombin      0
Stage            0
dtype: int64

In [8]:
# For Categorical type
df.select_dtypes(include=('object')).isna().sum()

Status             0
Drug            2025
Sex                0
Ascites         2246
Hepatomegaly    2427
Spiders         2590
Edema              0
dtype: int64

In [9]:
df_cat_col = df.select_dtypes(include=('object')).columns
for c in df_cat_col:
    df[c].fillna(df[c].mode().values[0], inplace=True)
    
df.select_dtypes(include=('object')).isna().sum()

Status          0
Drug            0
Sex             0
Ascites         0
Hepatomegaly    0
Spiders         0
Edema           0
dtype: int64

In [10]:
df['Stage'] = np.where(df['Stage'] == 4,1,0)

Preprocessing data

In [11]:
# replacing catagorical data with intigers.
df['Sex'] = df['Sex'].replace({'M':0, 'F':1})                                # Male : 0 , Female :1
df['Ascites'] = df['Ascites'].replace({'N':0, 'Y':1})                        # N : 0, Y : 1   
df['Drug'] = df['Drug'].replace({'D-penicillamine':0, 'Placebo':1})          # D-penicillamine : 0, Placebo : 1   
df['Hepatomegaly'] = df['Hepatomegaly'].replace({'N':0, 'Y':1})              # N : 0, Y : 1
df['Spiders'] = df['Spiders'].replace({'N':0, 'Y':1})                        # N : 0, Y : 1
df['Edema'] = df['Edema'].replace({'N':0, 'Y':1, 'S':-1})                    # N : 0, Y : 1, S : -1
df['Status'] = df['Status'].replace({'C':0, 'CL':1, 'D':-1})                 # 'C':0, 'CL':1, 'D':-1

In [12]:
# We will not be using 'Status' and 'N_days' as our features since this will cause data Leakage.
# Setting up Features and Target
X = df.drop(['Status', 'N_Days', 'Stage'], axis=1)
y = df.pop('Stage')

Model

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier 
from xgboost import XGBClassifier
# log_model = RandomForestClassifier(max_features=2,n_estimators=100,bootstrap=True)
log_model = XGBClassifier(learning_rate=0.75, max_depth=3, random_state=1, gamma=0, eval_metric='error')
# log_model = LogisticRegression(max_iter=450, solver='saga')
skf = StratifiedKFold(n_splits=150, random_state=2, shuffle=True)

acc=[]
def training(train, test, fold_no):
  X_train = train
  y_train = y.iloc[train_index]
  X_test = test
  y_test = y.iloc[test_index]
  log_model.fit(X_train, y_train)
  score = log_model.score(X_test,y_test)
  acc.append(score)
  print('For Fold {} the accuracy is {}'.format(str(fold_no),score))

fold_no = 1
for train_index,test_index in skf.split(X, y):
  train = X.iloc[train_index,:]
  test = X.iloc[test_index,:]
  training(train, test, fold_no)
  fold_no += 1
print()
print('Logestic Regression Mean Accuracy = ', np.mean(acc))

For Fold 1 the accuracy is 0.5217391304347826
For Fold 2 the accuracy is 0.5217391304347826
For Fold 3 the accuracy is 0.45652173913043476
For Fold 4 the accuracy is 0.4782608695652174
For Fold 5 the accuracy is 0.5217391304347826
For Fold 6 the accuracy is 0.45652173913043476
For Fold 7 the accuracy is 0.6086956521739131
For Fold 8 the accuracy is 0.45652173913043476
For Fold 9 the accuracy is 0.6739130434782609
For Fold 10 the accuracy is 0.6304347826086957
For Fold 11 the accuracy is 0.43478260869565216
For Fold 12 the accuracy is 0.4782608695652174
For Fold 13 the accuracy is 0.43478260869565216
For Fold 14 the accuracy is 0.5
For Fold 15 the accuracy is 0.5217391304347826
For Fold 16 the accuracy is 0.43478260869565216
For Fold 17 the accuracy is 0.5434782608695652
For Fold 18 the accuracy is 0.5869565217391305
For Fold 19 the accuracy is 0.5434782608695652
For Fold 20 the accuracy is 0.6086956521739131
For Fold 21 the accuracy is 0.4782608695652174
For Fold 22 the accuracy is 0.45652173913043476
For Fold 23 the accuracy is 0.3695652173913043
For Fold 24 the accuracy is 0.5434782608695652
For Fold 25 the accuracy is 0.43478260869565216
For Fold 26 the accuracy is 0.41304347826086957
For Fold 27 the accuracy is 0.43478260869565216
For Fold 28 the accuracy is 0.6086956521739131
For Fold 29 the accuracy is 0.45652173913043476
For Fold 30 the accuracy is 0.5217391304347826
For Fold 31 the accuracy is 0.6304347826086957
For Fold 32 the accuracy is 0.34782608695652173
For Fold 33 the accuracy is 0.6304347826086957
For Fold 34 the accuracy is 0.5217391304347826
For Fold 35 the accuracy is 0.4782608695652174
For Fold 36 the accuracy is 0.5869565217391305
For Fold 37 the accuracy is 0.6304347826086957
For Fold 38 the accuracy is 0.5217391304347826
For Fold 39 the accuracy is 0.4782608695652174
For Fold 40 the accuracy is 0.41304347826086957
For Fold 41 the accuracy is 0.5217391304347826
For Fold 42 the accuracy is 0.5869565217391305
For Fold 43 the accuracy is 0.5
For Fold 44 the accuracy is 0.34782608695652173
For Fold 45 the accuracy is 0.41304347826086957
For Fold 46 the accuracy is 0.5
For Fold 47 the accuracy is 0.5
For Fold 48 the accuracy is 0.6086956521739131
For Fold 49 the accuracy is 0.5434782608695652
For Fold 50 the accuracy is 0.5652173913043478
For Fold 51 the accuracy is 0.4222222222222222
For Fold 52 the accuracy is 0.4888888888888889
For Fold 53 the accuracy is 0.5333333333333333
For Fold 54 the accuracy is 0.6
For Fold 55 the accuracy is 0.5111111111111111
For Fold 56 the accuracy is 0.5555555555555556
For Fold 57 the accuracy is 0.4888888888888889
For Fold 58 the accuracy is 0.4444444444444444
For Fold 59 the accuracy is 0.4888888888888889
For Fold 60 the accuracy is 0.5333333333333333
For Fold 61 the accuracy is 0.6222222222222222
For Fold 62 the accuracy is 0.5111111111111111
For Fold 63 the accuracy is 0.5333333333333333
For Fold 64 the accuracy is 0.6444444444444445
For Fold 65 the accuracy is 0.6666666666666666
For Fold 66 the accuracy is 0.4444444444444444
For Fold 67 the accuracy is 0.5333333333333333
For Fold 68 the accuracy is 0.4444444444444444
For Fold 69 the accuracy is 0.5777777777777777
For Fold 70 the accuracy is 0.6
For Fold 71 the accuracy is 0.5111111111111111
For Fold 72 the accuracy is 0.5777777777777777
For Fold 73 the accuracy is 0.4222222222222222
For Fold 74 the accuracy is 0.4
For Fold 75 the accuracy is 0.4222222222222222
For Fold 76 the accuracy is 0.4888888888888889
For Fold 77 the accuracy is 0.5555555555555556
For Fold 78 the accuracy is 0.4
For Fold 79 the accuracy is 0.4666666666666667
For Fold 80 the accuracy is 0.5111111111111111
For Fold 81 the accuracy is 0.5333333333333333
For Fold 82 the accuracy is 0.6666666666666666
For Fold 83 the accuracy is 0.5333333333333333
For Fold 84 the accuracy is 0.4444444444444444
For Fold 85 the accuracy is 0.4666666666666667
For Fold 86 the accuracy is 0.5333333333333333
For Fold 87 the accuracy is 0.5777777777777777
For Fold 88 the accuracy is 0.4
For Fold 89 the accuracy is 0.4888888888888889
For Fold 90 the accuracy is 0.5111111111111111
For Fold 91 the accuracy is 0.5333333333333333
For Fold 92 the accuracy is 0.5333333333333333
For Fold 93 the accuracy is 0.35555555555555557
For Fold 94 the accuracy is 0.4888888888888889
For Fold 95 the accuracy is 0.4444444444444444
For Fold 96 the accuracy is 0.37777777777777777
For Fold 97 the accuracy is 0.4222222222222222
For Fold 98 the accuracy is 0.4222222222222222
For Fold 99 the accuracy is 0.3333333333333333
For Fold 100 the accuracy is 0.4888888888888889
For Fold 101 the accuracy is 0.5111111111111111
For Fold 102 the accuracy is 0.6222222222222222
For Fold 103 the accuracy is 0.4
For Fold 104 the accuracy is 0.5333333333333333
For Fold 105 the accuracy is 0.4888888888888889
For Fold 106 the accuracy is 0.6222222222222222
For Fold 107 the accuracy is 0.6222222222222222
For Fold 108 the accuracy is 0.4888888888888889
For Fold 109 the accuracy is 0.6222222222222222
For Fold 110 the accuracy is 0.35555555555555557
For Fold 111 the accuracy is 0.4444444444444444
For Fold 112 the accuracy is 0.37777777777777777
For Fold 113 the accuracy is 0.5111111111111111
For Fold 114 the accuracy is 0.35555555555555557
For Fold 115 the accuracy is 0.6444444444444445
For Fold 116 the accuracy is 0.4888888888888889
For Fold 117 the accuracy is 0.5555555555555556
For Fold 118 the accuracy is 0.5333333333333333
For Fold 119 the accuracy is 0.5111111111111111
For Fold 120 the accuracy is 0.4
For Fold 121 the accuracy is 0.5111111111111111
For Fold 122 the accuracy is 0.4666666666666667
For Fold 123 the accuracy is 0.4444444444444444
For Fold 124 the accuracy is 0.5333333333333333
For Fold 125 the accuracy is 0.4888888888888889
For Fold 126 the accuracy is 0.6
For Fold 127 the accuracy is 0.37777777777777777
For Fold 128 the accuracy is 0.5555555555555556
For Fold 129 the accuracy is 0.5555555555555556
For Fold 130 the accuracy is 0.4444444444444444
For Fold 131 the accuracy is 0.4888888888888889
For Fold 132 the accuracy is 0.5555555555555556
For Fold 133 the accuracy is 0.5333333333333333
For Fold 134 the accuracy is 0.4444444444444444
For Fold 135 the accuracy is 0.5111111111111111
For Fold 136 the accuracy is 0.4888888888888889
For Fold 137 the accuracy is 0.4666666666666667
For Fold 138 the accuracy is 0.3333333333333333
For Fold 139 the accuracy is 0.4888888888888889
For Fold 140 the accuracy is 0.4888888888888889
For Fold 141 the accuracy is 0.6666666666666666
For Fold 142 the accuracy is 0.6
For Fold 143 the accuracy is 0.5111111111111111
For Fold 144 the accuracy is 0.5777777777777777
For Fold 145 the accuracy is 0.5777777777777777
For Fold 146 the accuracy is 0.4222222222222222
For Fold 147 the accuracy is 0.4444444444444444
For Fold 148 the accuracy is 0.6444444444444445
For Fold 149 the accuracy is 0.5555555555555556
For Fold 150 the accuracy is 0.4888888888888889

Logestic Regression Mean Accuracy =  0.5051175523349436

In [14]:
from sklearn.metrics import classification_report
log_model_predict = log_model.predict(test)
log_model_predict_proba = log_model.predict_proba(test)

print(classification_report(y.iloc[test_index], log_model_predict))

              precision    recall  f1-score   support

           0       0.47      0.41      0.44        22
           1       0.50      0.57      0.53        23

    accuracy                           0.49        45
   macro avg       0.49      0.49      0.48        45
weighted avg       0.49      0.49      0.49        45

In [15]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve, auc

fpr, tpr, threshold = roc_curve(y.iloc[test_index], log_model_predict_proba[:,1])
roc_auc = auc(fpr, tpr)

print('AUC : ', roc_auc_score(y.iloc[test_index], log_model_predict_proba[:,1]))

AUC :  0.541501976284585

In [ ]:
y_pred = model.predict(test_data)

In [ ]:
X_test['Stage'] = y_pred
submission = X_test['Stage'].astype('float64')
submission.index = X_test.index

In [ ]:
submission.to_csv('submission.csv', index=False)